[project]
name = "pyside6-uv-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyside6>=6.8.1.1",
]

[dependency-groups]
dev = [
    "pip>=24.3.1",
    "pyinstaller>=6.11.1",
]
